# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 765c9bef76cdaa0e80ca03b57e3b01c7067093eed06ad0ec85a77870fbd8c5983e64f95d15d031a4d59dee93b5df4d8e74fb3bf48c32c48f36bdac8dc078e93b

test:
  secret_key_base: 4314afcf33d0e9f0531eb3d86212f44f966cad71833d6d7310a347ca45f94108e9e96233c3914e76dd514364ba4a9fa4b2fad98ed3c037545a4c70440e3e18c4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
