version: '3'
services:
  db:
    image: postgres
  back:
    build: dragon-store-back
    image: yovasx2/dragon-store-back
    volumes:
      - ./dragon-store-back:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
